name: C Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build
      run: |
        gcc -o program src/main.c src/worker.c -Iinclude
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Create input file
      run: |
        cat > data/workers.txt << EOF
        Иванов;Иван;Иванович;123456;Россия;Московская;Раменский;Москва;Ленина;10;25;Русский;1985;5;15;3;1001;Высшее;2020
        Петров;Петр;Петрович;654321;Россия;Ленинградская;Всеволожский;СПб;Невский;20;5;Русский;1990;3;10;2;1002;Среднее;2019
        Сидоров;Сидор;Сидорович;111222;Россия;Новосибирская;Новосибирский;Новосибирск;Гагарина;15;7;Русский;1988;8;22;1;1003;Высшее;2020
        EOF
    
    - name: Run program
      run: ./program
    
    - name: Check output
      run: |
        if [ -f "data/workers_2020.txt" ]; then
          echo "✅ Файл найден!"
          cat data/workers_2020.txt
        else
          echo "❌ Файл не найден"
          ls -la data/
        fi
